God.destroy_all

God.create :name => "Achelois", :description => "One of the moon goddesses."
God.create :name => "Achelous", :description => "The patron god of the Achelous river."
God.create :name => "Aeolus", :description => "(a.k.a. Aeolos, Aiolos, Aiolus, Eolus) God of air and the winds."
God.create :name => "Aether", :description => "(a.k.a. Aither, Akmon, Ether) God of light and the atmosphere."
God.create :name => "Alastor", :description => "God of family feuds."
God.create :name => "Alcyone", :description => "One of the seven daughters of Atlas and Pleione."
God.create :name => "Alectrona", :description => "Early Greek goddess of the sun."
God.create :name => "Amphitrite", :description => "(a.k.a. Salacia) The wife of Poseidon and a Nereid."
God.create :name => "Antheia", :description => "Goddess of gardens, flowers, swamps, and marshes."
God.create :name => "Aphaea", :description => "(a.k.a. Aphaia) A Greek goddess who was worshipped exclusively at a single sanctuary on the island of Aegina the Saronic Gulf."
God.create :name => "Aphrodite", :description => "(a.k.a. Anadyomene, Turan, Venus) Goddess of love and beauty."
God.create :name => "Apollo", :description => "(a.k.a. Apollon, Apulu, Phoebus) God of the sun, music, healing, and herding."
God.create :name => "Ares", :description => "(a.k.a. Enyalius, Mars, Aries) God of chaotic war."
God.create :name => "Aristaeus", :description => "(a.k.a. Aristaios) Patron god of animal husbandry, bee-keeping, and fruit trees."
God.create :name => "Artemis", :description => "(a.k.a. Agrotora, Amarynthia, Cynthia, Kourotrophos, Locheia, Orthia, Phoebe, Potnia Theron) Goddess of hunting, and nursing."
God.create :name => "Asclepius", :description => "(a.k.a. Aesculapius, Asklepios) God of health and medicine."
God.create :name => "Astraea", :description => "The Star Maiden - a goddess of justice, included in Virgo and Libra mythologies."
God.create :name => "Até", :description => "Goddess of mischief."
God.create :name => "Athena", :description => "(a.k.a. Asana, Athene, Minerva, Menerva) Goddess of wisdom, poetry, art, and the strategic side of war."
God.create :name => "Atlas", :description => "The Primordial Titan who carried the world on his back."
God.create :name => "Atropos", :description => "(a.k.a. Aisa, Morta) One of The Fates - She cut the thread of life and chose the manner of a persons death."
God.create :name => "Attis", :description => "The (minor) god of rebirth."
God.create :name => "Bia", :description => "The goddess of force."
God.create :name => "Boreas", :description => "(a.k.a. Aquilo, Aquilon) The North Wind. One of the Anemoi (wind gods)."
God.create :name => "Brizo", :description => "Protector of Mariners."
God.create :name => "Caerus", :description => "(a.k.a. Kairos, Occasio, Tempus) The (minor) god of luck and opportunity."
God.create :name => "Calliope", :description => "One of the Muses. Represented epic poetry."
God.create :name => "Calypso", :description => "(a.k.a. Kalypso) The sea nymph who held Odysseus prisoner for seven years."
God.create :name => "Castor", :description => "(a.k.a. Castore, Kastor) One of the twins who represent Gemini."
God.create :name => "Celaeno", :description => "The name of a wife of Poseidon."
God.create :name => "Cerus", :description => "The wild bull tamed by Persephone, made into the Taurus constellation."
God.create :name => "Ceto", :description => "(a.k.a. Keto) a sea monster goddess who was also the mother of other sea monsters."
God.create :name => "Chaos", :description => "(a.k.a. Khaos) The nothingness that all else sprung from."
God.create :name => "Charon", :description => "(a.k.a. Charun) The Ferryman of Hades. He had to be paid to help one cross the river Styx."
God.create :name => "Chronos", :description => "(a.k.a. Chronus, Khronos) God of time."
God.create :name => "Circe", :description => "(a.k.a. Kirke) A goddess who transformed her enemies into beasts."
God.create :name => "Clio", :description => "One of the Muses. She represented History."
God.create :name => "Clotho", :description => "(a.k.a. Nona) One of the Fates - Spun the thread of life from her distaff onto her spindle."
God.create :name => "Crios", :description => "The crab who protected the sea nymphs, made into the Cancer constellation."
God.create :name => "Cronus", :description => "(a.k.a. Cronos, Kronos, Saturn) God of agriculture, father of the Titans."
God.create :name => "Cybele", :description => "(a.k.a. Agdistis, Magna Mater, Meter, Meter Oreie) Goddess of caverns, mountains, nature and wild animals."
God.create :name => "Demeter", :description => "(a.k.a. Ceres, Demetra, Tvath) Goddess of the harvest."
God.create :name => "Dinlas", :description => "Guardian of the ancient city of Lamark, where wounded heroes could heal after battle."
God.create :name => "Dionysus", :description => "(a.k.a. Bacchus, Dionysos, Liber) God of wine and pleasure."
God.create :name => "Doris", :description => "A Sea Nymph, mother of the Nereids."
God.create :name => "Eileithyia", :description => "(a.k.a. Eileithyiai, Eilithia, Eilythia, Eleuthia, Ilithia, Ilithyia, Lucina) Goddess of childbirth."
God.create :name => "Eireisone", :description => "The deity who embodied the sacred ceremonial olive branch."
God.create :name => "Electra", :description => "(a.k.a. Atlantis) One of the seven Pleiades."
God.create :name => "Elpis", :description => "(a.k.a. Spes) The spirit of Hope."
God.create :name => "Enyo", :description => "(a.k.a. Bellona) A (minor) goddess of war, connected to Eris."
God.create :name => "Eos", :description => "(a.k.a. Aurora, Eosphorus, Mater Matuta, Thesan) Goddess of the Dawn."
God.create :name => "Erato", :description => "One of the Muses - represents Lyrics/Love Poetry."
God.create :name => "Erebus", :description => "(a.k.a. Erebos) God of darkness."
God.create :name => "Eris", :description => "(a.k.a. Discordia) Goddess of strife, connected to Enyo."
God.create :name => "Eros", :description => "(a.k.a. Amor, Cupid, Eleutherios) God of love, procreation and sexual desire."
God.create :name => "Eurus", :description => "(a.k.a. Euros, Vulturnus) The East Wind - One of the Anemoi (wind gods)."
God.create :name => "Euterpe", :description => "One of the Muses - represents Music/Lyrics/Poetry."
God.create :name => "Gaia", :description => "(a.k.a. Celu, Gaea, Terra) Goddess of the Earth, also known as Mother Earth."
God.create :name => "Glaucus", :description => "(a.k.a. Glacus, Glaukos) A fisherman turned immortal, turned Argonaut, turned a god of the sea."
God.create :name => "Hades", :description => "(a.k.a. Aita, Dis Pater, Haidou, Orcus, Plouton, Pluto) God of the Dead, King of the Underworld."
God.create :name => "Harmonia", :description => "(a.k.a. Concordia) Goddess of Harmony and Concord."
God.create :name => "Hebe", :description => "(a.k.a. Juventas) Goddess of youth."
God.create :name => "Hecate", :description => "(a.k.a. Hekat, Hekate, Trivia) Goddess of magic, witchcraft, ghosts, and the undead."
God.create :name => "Helios", :description => "(a.k.a. Sol) God of the Sun."
God.create :name => "Hemera", :description => "(a.k.a. Amar, Dies, Hemere) Goddess of daylight."
God.create :name => "Hephaestus", :description => "(a.k.a. Hephaistos, Vulcan, Sethlans, Mulciber) God of fire and blacksmithing who created weapons for the Gods."
God.create :name => "Hera", :description => "(a.k.a. Juno, Uni) Goddess of goddesses, women, and marriage and wife of Zeus."
God.create :name => "Heracles", :description => "(a.k.a. Herakles, Hercules, Hercle) An immortal hero of many Greek legends, the strongest man on Earth."
God.create :name => "Hermes", :description => "(a.k.a. Pyschopompus, Mercury, Turms) God of commerce and travel, and messenger of the gods."
God.create :name => "Hesperus", :description => "(a.k.a. Hesperos, Vesper) The Evening Star."
God.create :name => "Hestia", :description => "(a.k.a. Vesta) Greek goddess of the home and fertility. One of the Hesperides."
God.create :name => "Hygea", :description => "(a.k.a. Hygieia, Salus) Goddess of cleanliness and hygeine."
God.create :name => "Hymenaios", :description => "(a.k.a. Hymenaeus, Hymen) God of weddings."
God.create :name => "Hypnos", :description => "(a.k.a. Somnus) God of sleep."
God.create :name => "Iris", :description => "Goddess of rainbows."
God.create :name => "Khione", :description => "The goddess of snow and daughter of the North Wind (Boreas)."
God.create :name => "Kotys", :description => "(a.k.a. Cotys, Cottyto, Cottytus) A Dionysian goddess whose celebrations were wild and liscivious."
God.create :name => "Kratos", :description => "A god of strength and power."
God.create :name => "Lacheses", :description => "(a.k.a. Decima) One of the Fates. Measured the thread of life with her rod."
God.create :name => "Maia", :description => "(a.k.a. Mya, Fauna, Maia Maiestas, Bono Dea) One of the seven Pleiades, Goddess of fields."
God.create :name => "Mania", :description => "(a.k.a. Mania, Manea) Goddess of insanity and the dead."
God.create :name => "Melpomene", :description => "One of the Muses - represented Tragedy."
God.create :name => "Merope", :description => "One of the seven Pleiades, married to king Sisyphos."
God.create :name => "Metis", :description => "Titan goddess of wisdom."
God.create :name => "Momus", :description => "(a.k.a. Momos) God of satire, writers, and poets."
God.create :name => "Morpheus", :description => "God of dreams and sleep."
God.create :name => "Nemesis", :description => "(a.k.a. Rhamnousia, Invidia) Goddess of retribution (vengeance)."
God.create :name => "Nereus", :description => "(a.k.a. Phorcys, Phorkys) Titan God who Fathered the Nereids. God of the Sea before Poseidon."
God.create :name => "Nike", :description => "(a.k.a. Victoria, Nice) Goddess of victory."
God.create :name => "Notus", :description => "(a.k.a. Auster) The South Wind. One of the Anemoi (wind gods)."
God.create :name => "Nyx", :description => "(a.k.a. Nox) Goddess of night."
God.create :name => "Oceanus", :description => "Titan god of the ocean."
God.create :name => "Pallas", :description => "A giant who was one of the ancient Titan gods of war."
God.create :name => "Pan", :description => "(a.k.a. Faunus, Inuus) God of woods, fields, and flocks. Also a Satyr."
God.create :name => "Peitha", :description => "(a.k.a. Peitho, Suadela) Goddess of persuasion."
God.create :name => "Persephone", :description => "(a.k.a. Persephassa, Persipina, Persipnei, Persephatta, Proserpina, Kore, Kora, Libera) Goddess of the Spring, she lives off-season in the Underworld."
God.create :name => "Pheme", :description => "(a.k.a. Fama) Goddess of fame and gossip."
God.create :name => "Phosphorus", :description => "(a.k.a. Phosphor, Lucifer) The Morning Star."
God.create :name => "Plutus", :description => "God of wealth."
God.create :name => "Pollux", :description => "(a.k.a. Polydeuces) One of the twins who represent Gemini."
God.create :name => "Polyhymnia", :description => "One of the Muses - represents sacred poetry and geometry."
God.create :name => "Pontus", :description => "(a.k.a. Pontos) Ancient god of the deep sea."
God.create :name => "Poseidon", :description => "(a.k.a. Neptune, Nethuns, Neptunus) God of the sea and earthquakes."
God.create :name => "Priapus", :description => "(a.k.a. Priapus, Mutinus, Mutunus) A (minor) god of gardens and fertility, best known for having an enormous penis."
God.create :name => "Pricus", :description => "The immortal father of sea-goats, made into the Capricorn constellation."
God.create :name => "Proteus", :description => "An early sea god before Poseidon."
God.create :name => "Rhea", :description => "(a.k.a. Cybele) Goddess of nature."
God.create :name => "Selene", :description => "(a.k.a. Luna) Goddess of the Moon and the 'mother' of vampires."
God.create :name => "Sterope", :description => "(a.k.a. Asterope) One of the seven Pleiades, who bore a child of Ares."
God.create :name => "Styx", :description => "A Naiad who was the first to aid Zeus in the Titan war. (Not to be confused with the river Styx)."
God.create :name => "Tartarus", :description => "(a.k.a. Tartaros, Tartarizo) God of the depths of the Underworld - a great storm pit - and the father of Typhon"
God.create :name => "Taygete", :description => "(a.k.a. Taygeti, Taigeti) One of the seven Pleiades, a mountain nymph."
God.create :name => "Terpsichore", :description => "One of the Muses - represented Dancing."
God.create :name => "Thalia", :description => "One of the Muses - represented Comedy."
God.create :name => "Thanatos", :description => "(a.k.a. Mors) God of death."
God.create :name => "Themis", :description => "Ancient goddess of divine order, law, and custom."
God.create :name => "Thetis", :description => "Leader of the Nereids, a shapeshifter, and a prophet."
God.create :name => "Triton", :description => "(a.k.a. Triton) Trumpeter of the sea and messenger of the deep."
God.create :name => "Tyche", :description => "(a.k.a. Fortuna, Nortia) Goddess of fortune and prosperity."
God.create :name => "Typhon", :description => "(a.k.a. Typhaon, Typhoeus, Typhus) God of monsters, storms, and volcanoes. Challenged Zeus for control of Mount Olympus"
God.create :name => "Urania", :description => "One of the Muses - represented Astronomy and Astrology."
God.create :name => "Uranus", :description => "(a.k.a. Ouranos, Caelus) God of the sky and the heavens. Father of the Titans."
God.create :name => "Zelus", :description => "The god of zeal, rivalry, and jealousy."
God.create :name => "Zephyrus", :description => "(a.k.a. Zephyros, Favonius, Zephyr) The West Wind. One of the Anemoi (wind gods)."